name: PR Preview Deploy

on:
  pull_request:
    branches: [main]

jobs:
  build-and-deploy-preview:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll Site
      run: bundle exec jekyll build -d preview-site

    - name: Deploy Preview to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./preview-site
        destination_dir: docs/preview/pr-${{ github.event.pull_request.number }}
        keep_files: true
        commit_message: "Preview for PR #${{ github.event.pull_request.number }}"
    
    - name: Comment preview URL on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const url = `https://${owner}.github.io/${repo}/preview/pr-${pr.number}/`;

            const body = `🔍 Preview your changes here (it may take time to be built): [**View Preview**](${url})`;

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: pr.number,
              body,
            });